# Generated by Django 5.2.6 on 2025-10-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("categoryId", models.IntegerField()),
                ("price", models.IntegerField()),
                ("priceInfo", models.CharField(max_length=255)),
                ("rating", models.FloatField()),
                ("description", models.TextField()),
            ],
        ),
    ]
