# Generated by Django 5.2.6 on 2025-10-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="reviews",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="priceInfo",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
    ]
